# Generated by Django 3.2.6 on 2022-11-15 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('place', models.CharField(blank=True, max_length=255, null=True)),
                ('bic', models.CharField(blank=True, max_length=15, null=True)),
                ('c_account', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Банк',
                'verbose_name_plural': 'Банки',
            },
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': 'Группа товаров',
                'verbose_name_plural': 'Группы товаров',
            },
        ),
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Единица',
                'verbose_name_plural': 'Единицы',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('supplier_price', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Закуп. цена')),
                ('retail_price', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Розн. цена')),
                ('minimal_amount', models.BigIntegerField(verbose_name='Норма запаса')),
                ('all_amount', models.BigIntegerField(verbose_name='Кол-во')),
                ('weight', models.IntegerField(verbose_name='Масса')),
                ('actual', models.BooleanField(verbose_name='Актуальный')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.countries', verbose_name='Страна')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.groups', verbose_name='Группа товаров')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.units', verbose_name='Единица')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
