# Generated by Django 3.2.6 on 2022-11-15 09:10

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20221115_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banks',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
