# Generated by Django 3.2.6 on 2022-11-15 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_banks_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banks',
            name='place',
        ),
        migrations.AlterField(
            model_name='banks',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
