# Generated by Django 3.2.6 on 2022-11-19 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_gooditem_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gooditem',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
