# Generated by Django 3.2.6 on 2022-11-20 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20221119_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='total_cost',
        ),
    ]
