# Generated by Django 3.2.6 on 2022-11-20 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20221120_1534'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='good',
            options={'ordering': ('-pk',), 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.RemoveField(
            model_name='good',
            name='country',
        ),
        migrations.AddField(
            model_name='good',
            name='countries',
            field=models.ManyToManyField(to='shop.Country'),
        ),
    ]
