# Generated by Django 3.2.6 on 2022-11-20 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20221120_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='good',
            name='countries',
        ),
    ]
