# Generated by Django 3.2.6 on 2022-11-20 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_good_countries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='good',
            name='countries',
        ),
    ]
